version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ai-ml-network

  # Backend (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend/.env:/app/.env:ro
    networks:
      - ai-ml-network
    restart: unless-stopped

networks:
  ai-ml-network:
    driver: bridge

volumes:
  backend_data: